version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "16:10"
    timezone: "Australia/Sydney"
  open-pull-requests-limit: 50
  target-branch: 3.x-develop
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "16:10"
    timezone: "Australia/Sydney"
  open-pull-requests-limit: 50
  target-branch: 4.x-develop

