version: 2
registries:
  drupal-packages:
    type: composer-repository
    url: https://packages.drupal.org/8
    username: "token"
    password: "any-password"
updates:
- package-ecosystem: composer
  directory: "/"
  ignore:
    - dependency-name: "drupal/core*"
      update-types: ["version-update:semver-major"]
  groups:
    drupal-core:
      patterns:
        - "drupal/core*"
  schedule:
    interval: daily
    time: "16:00"
    timezone: "Australia/Sydney"
  registries:
    - drupal-packages
  open-pull-requests-limit: 30
  target-branch: 4.x-develop
