editor.image_upload_settings.0: 
  type: mapping
  label: 'Image upload settings (disabled)'
  mapping:
    status:
      type: boolean
      label: 'Enable image uploads'
      nullable: true
    scheme:
      type: string
      label: 'File storage'
      nullable: true
    directory:
      type: string
      label: 'Upload directory'
      nullable: true
    max_size:
      type: bytes
      label: 'Maximum file size'
      nullable: true
    max_dimensions:
      type: mapping
      label: 'Maximum dimensions'
      mapping:
        width:
          type: integer
          nullable: true
        height:
          type: integer
          nullable: true